### ISSUE TITLE
Missing libraries msvcp120.dll and msvcr120.dll

### ISSUE THREAD

**Issue by victormunoz** [MediaArea/MediaConch#125]
I have installed the 64bits windows version of CLI (v16.0.3) downloaded from this link [https://mediaarea.net/download/binary/mediaconch/16.03/MediaConch_CLI_16.03_Windows_x64.zip](https://mediaarea.net/download/binary/mediaconch/16.03/MediaConch_CLI_16.03_Windows_x64.zip) in a clean computer with Windows 10.

When the program is started an error message appears saying that the libraries msvcp120.dll and msvcr120.dll are missing.

**Comment by JeromeMartinez** [comment]
We were compiling some libraries with "MultiThreadedDLL" for both the GUI and the CLI, as Qt (the UI library) is requesting "MultiThreadedDLL", but depending of such libraries was actually not intended for the CLI (trying to have only one file with all libraries staticly included, in order to have few files only in the archive).
Now I created a script for handling both scenario, GUI still needs these msvcp120.dll (and it is in the archive) and CLI doe not need it anymore.
You can test https://mediaarea.net/temp/MediaConch_CLI_16.03.20160427_Windows_x64.zip and it is included in next official release end of this month.
