### ISSUE TITLE
Check: Results for "MediaInfo" and "MediaTrace" empty

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch#86]
On Xubuntu Precie (12.04.3 LTS), clicking on the "eye" symbol for "MediaInfo" or "MediaTrace" after checking a file, an empty window with a search field is displayed.

Anyone else also having this issue?
Thanks.

**Comment by pjotrek-b** [comment]
Also applies to Ubuntu Trusty Tahr (14.04.3 LTS) build (64bit).

**Comment by tribouille** [comment]
Hi,
is this happen when your implementation report or policy report says valid with a validation internal error? ( #85 )
I will check later, but it can be due to the installation (not using the correct MediaInfoLib or LibZen)
Not sure, but I think this problem is related to #85 and #84 .
Wrong libs make the reports wrong which make the validation impossible.

**Comment by pjotrek-b** [comment]
@tribouille:
You were right. This issue was fixed by solving the dependency issues of MediaInfoLib/LibZen (See issue #84).

Seems to work fine now.
Reports are properly populated with meaningful data :)
